#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:05:00


# functions

str_index() {    
                
                ############# ############# ############# ############# ############# ############# 
                ############     find the first index of the substring in a string      ########### 
                ############# ############# ############# ############# ############# #############   

			if [ $# -lt 2 ]; then							# usage dello script							
			    echo $0: "usage: str_index <string> <substrin> "
			    return 1;		    
			fi       

                x="${1%%$2*}";   
                [[ $x = $1 ]] && echo -1 || echo ${#x}; 
            };


remove_extx () {
	
			local result=$( echo ` basename $1 | cut -d '.' -f 1 ` )
			
			local idx=$( str_index ${result} '.' )
			
			if [ ${idx} -ne -1 ]; then
				
				local extension="${result##*.}"		
				
				if [ "${extension}" == "nii" ]; then
					local result=$( echo ` basename $result | cut -d '.' -f 1 ` )	
				fi 
			fi
			
			echo ${result}
				
				}


#parse config.json for input parameters (here, we are pulling "t1") --> communication with BL
t1=$(jq -r .t1 config.json)
affine=$(jq -r .affine config.json)
mask=$(jq -r .mask config.json)

echo ${mask}
echo ${affine}
if [ -n "${affine}" ]; then
	affine_opt=" --affine ${affine} "

fi
mask=$(jq -r .mask config.json)
if [ -n "${mask}" ]; then
	mask_opt=" --mask ${mask} "
fi

outputdir_0=${PWD}"/outputdir"
outputdir_1=${PWD}"/T1_reoriented"
outputdir_2=${PWD}"/T1_reoriented_N4"

template='./data/MNI152_T1_1mm.nii.gz'
singularity exec -e docker://brainlife/ants:2.2.0.1 bash T1Wbasicpreproc.sh -i $t1 -t ${template} ${affine_opt}  ${mask_opt} --outputdir ${outputdir_0}

# save outputfile 

mkdir -p ${outputdir_1}
mkdir -p ${outputdir_2}

prefix=$( remove_extx $( basename ${t1} ) )

cp ${outputdir_0}'/'${prefix}"_reoriented.nii.gz"	${outputdir_1}
cp ${outputdir_0}'/'${prefix}"_reoriented_N4.nii.gz"	${outputdir_2}

